repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.9.2
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        types: [rst]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [python]
        args: [--line-length=88]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        types: [python]
        # exclude: setup.py src/__init__.py
        additional_dependencies: [
            flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
            flake8-docstrings, flake8-eradicate, flake8-print, flake8-rst-docstrings,
            flake8-todo, pep8-naming, pydocstyle,
        ]
        args:
            - --ignore=D100 D104 RST201 RST203 RST301
            - --max-line-length=88
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
