min_size: 3
# minimum size of a single group

n_candidates: 250
# candidate groupings to draw from which the best one is picked

initial_seed: 0

is_names_file_stored_local: True
# if True is expected to be stored at src/data/names.csv

names_file_url:
# link to names file
