name: random-group

channels:
  - defaults
  - conda-forge
  - pytask

dependencies:
  - python=3.8
  - pip

  - ipykernel
  - jupyterlab
  - nb_conda_kernels
  - conda-build

  - pandas
  - numpy
  - scipy

    # - joblib
    # - numba

  - pytest
  - pdbpp
  - flake8

  - pip:
      - black
      - blackcellmagic
      - pre-commit
