name: randomgroups

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - click

  - ipykernel
  - jupyterlab
  - nb_conda_kernels
  - conda-build

  - pandas
  - numpy

  - pytest
  - pdbpp
  - flake8

  - pip:
      - black
      - blackcellmagic
      - pre-commit
