package:
  name: randomgroups
  version: "0.0.1"

source:
    git_url: https://github.com/timmens/random-grouping.git

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python >=3.6

  run:
    - python >=3.6
    - click
    - numpy >=1.16
    - pandas >=0.24

about:
  home: https://github.com/timmens/random-grouping
  license: MIT
  license_file: LICENSE
  summary: Random recurring grouping generator.
