name: Pre-Commit

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

jobs:

  run-pre-commits:
    
    name: Run pre-commit.
    runs-on: ubuntu-latest

    steps:
      - name: pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          python-version: '3.9'
